; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define MyAppVersion "1.0.0"

[Setup]
AppName=Osuruktan Dert Button
AppVersion={#MyAppVersion}
AppPublisher=SatanJäger
AppVerName=Osuruktan Dert Button {#MyAppVersion}
DefaultDirName={autopf}\OsuruktanDertButton
DefaultGroupName=Osuruktan Dert Button
OutputDir=installer
OutputBaseFilename=OsuruktanDertButton-Setup-{#MyAppVersion}
SetupIconFile=AppIcon.ico
Compression=lzma
SolidCompression=yes

[Files]
Source: "publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\Osuruktan Dert Button"; Filename: "{app}\OsuruktanDertButton.exe"
Name: "{group}\Uninstall - Osuruktan Dert Button"; Filename: "{uninstallexe}"
Name: "{autodesktop}\Osuruktan Dert Button"; Filename: "{app}\OsuruktanDertButton.exe"

[Run]
Filename: "{app}\OsuruktanDertButton.exe"; Description: "Osuruktan Dert Button'u şimdi çalıştır"; Flags: nowait postinstall skipifsilent

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"